[package]
authors = ["Kenneth Koski <kennethkoski@gmail.com>"]
edition = "2018"
readme = "README.md"
name = "povdagger"
version = "0.1.0"

[dependencies]
apa102-spi = "0.2"
cortex-m = "0.6"
cortex-m-rt = "0.6"
cortex-m-semihosting = "0.3"
embedded-hal = "0.2"
feather_m0 = "0.3"
panic-halt = "0.2"
smart-leds = "0.2"
tinybmp = "0.1"

[[bin]]
name = "povdagger"
test = false
bench = false

[profile.release]
codegen-units = 1
debug = true
lto = true
