#!/bin/bash

set -euxo pipefail

ARCH="thumbv7em-none-eabihf"

cargo build --release
cargo objcopy -- -O binary target/$ARCH/release/povdagger{,.bin}
./uf2conv.py -c -f SAMD51 -b 0x4000 -o target/$ARCH/release/povdagger{.uf2,.bin}
sudo cp target/$ARCH/release/povdagger.uf2 /media/ken/FEATHERBOOT/CURRENT.UF2
